name: kiwi
description: A simple compile-time dependency injection library for Dart and Flutter.
version: 0.1.0
author: Romain Rastel <lets4r@gmail.com>
homepage: https://github.com/letsar/kiwi

environment:
  sdk: '>=2.0.0 <3.0.0'

dev_dependencies:
  test: ^1.0.0
